name: gramps_publish
on: push
jobs:
  build: 
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install gramps
        run: sudo apt-get -y install gramps

      - name: Build Gramps narrated Website
        run: |
            sed -e "s~<mediapath>.*</mediapath>~<mediapath>`pwd`</mediapath>~g" knuthp.xml| gzip > knuthp.gramps && gramps --create=knuthp --import=./knuthp.gramps
            ./scripts/gramps_html